spring:
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:db/schema-postgresql.sql
      table-prefix: pbf.BATCH_
    job:
      # Don't run at startup since the job is scheduled
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: pbf
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.batch_size: 1000
        order_inserts: true
      javax.persistence.create-database-schemas: true